#!/usr/bin/env bash

export CONTECO_LABEL="elasticsearch.base - ContEco"
export CONTECO_DESCRIPTION="Official Elasticsearch base image with minor configuration change."

export CONTECO_TYPE="elasticsearch"
export CONTECO_NAME="base"
export CONTECO_TAG="7.8.0"

export CONTECO_BASE="external.elasticsearch:7.8.0"
export CONTECO_BUILD="image-base"
