#!/usr/bin/env bash

export CONTECO_LABEL="elasticsearch.base - ContEco"
export CONTECO_DESCRIPTION="Official Elasticsearch base image with minor configuration change."

export CONTECO_TYPE="elasticsearch"
export CONTECO_NAME="base"
export CONTECO_TAG="7.9.2"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="elasticsearch:7.9.2"
