#!/usr/bin/env bash

export CONTECO_LABEL="Conteco elasticsearch base"
export CONTECO_DESCRIPTION="The ElasticSearch base image."

export CONTECO_TYPE="elasticsearch"
export CONTECO_NAME="base"
export CONTECO_TAG="6.8.1"

export CONTECO_BASE="external.elasticsearch:6.8.1"
export CONTECO_BUILD="image-base"
