---
version: '3'
services:

  service:
##### BEGIN ${CONTECO_TYPE}.${CONTECO_NAME}/docker-compose/service #####
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.${CONTECO_TYPE}.${CONTECO_NAME}:${CONTECO_TAG}
    environment:
      - cluster.name=${CONTECO_TYPE}.${CONTECO_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
      - discovery.type=single-node     
##### BEGIN ${CONTECO_TYPE}.${CONTECO_NAME}/docker-compose/service #####
    ports:
      - 9200:9200
    deploy:
      mode: replicated
    networks:
      - ${CONTECO_ECOSYSTEM}_overlay

networks:
  ${CONTECO_ECOSYSTEM}_overlay:
    external: true