---
version: '3'
services:

# START SERVICE elasticsearch.base
  elasticsearch:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.elasticsearch.base:7.1.1
    environment: [${CONTECO_DC_ELASTICSEARCH_BASE_ENVIRONMENT}] 
    command: [${CONTECO_DC_ELASTICSEARCH_BASE_COMMAND}]
    volumes: [${CONTECO_DC_ELASTICSEARCH_BASE_VOLUMES}]
    ports: [${CONTECO_DC_ELASTICSEARCH_BASE_PORTS}]
    networks: [${CONTECO_DC_ELASTICSEARCH_BASE_NETWORKS}]
    deploy:
      mode: ${CONTECO_DC_ELASTICSEARCH_BASE_DEPLOY_MODE}
      resources: 
        limits: 
          cpus: '${CONTECO_DC_ELASTICSEARCH_BASE_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_ELASTICSEARCH_BASE_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_ELASTICSEARCH_BASE_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_ELASTICSEARCH_BASE_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
# END SERVICE elasticsearch.base

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
